package models.Usuarios;

public enum Permiso {
    CREAR_ORGANIZACIONES,
    VER_ORGANIZACIONES,
    EDITAR_ORGANIZACIONES,
    ELIMIAR_ORGANIZACIONES,

    CREAR_SECTORES,
    VER_SECTORES,
    EDITAR_SECTORES,
    ELIMINAR_SECTORES,

    VER_PETICIONES,
    ACEPTAR_PETICIONES,
    RECHAZAR_PETICIONES,

    REGISTRAR_MEDICIONES,

    VER_REPORTES,

    VER_RECOMENDACIONES,

    CREAR_TRAYECTOS,
    VER_TRAYECTOS,
    EDITAR_TRAYECTOS,
    ELIMINAR_TRAYECTOS,

    CALCULAR_HUEYA_CARBONO,
}
